"""audit hash chain + chain state

Revision ID: bd548f798ec3
Revises: 1a6f72c8d02f
Create Date: 2026-07-19 15:19:42.797532
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'bd548f798ec3'
down_revision: str | None = '1a6f72c8d02f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_chain_state',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('last_hash', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('org_id')
    )
    # server_default='' keeps this safe on tables that already contain rows
    # (Postgres rejects a NOT NULL column added without a default).
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_ts', sa.String(length=32), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('prev_hash', sa.String(length=64), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('entry_hash', sa.String(length=64), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_column('entry_hash')
        batch_op.drop_column('prev_hash')
        batch_op.drop_column('event_ts')

    op.drop_table('audit_chain_state')
    # ### end Alembic commands ###
